### ISSUE TITLE
Add support for additional flags in main binary

### ISSUE THREAD

**Issue by cpuguy96** [jhaco/SMDataTools#2]
## Current
Main binary only uses `--script` as a flag and doesn't support passing in the input/output locations when script runs (handle by config.ini file instead). 

## Desired
Add parsing of `--input` and `--output` flags in main binary to use in both script types. Afterwards, the config used can be specified by another flag `--config`. All flags can be defined and read from the config file instead of the half and half approach currently done.

**Comment by jhaco** [comment]
Added support for overriding config.ini directory values by passing in a directory to their respective flags, and support for running multiple flags/scripts in the command-line.
